# API Docs

### BASE ENDPOINT TEST
GET http://localhost:3000/

## CRUD Client 

### Create a client
POST http://localhost:3000/api/clients
Content-Type: application/json
# Authorization: 

{
    "clientName": "Derrick Banners"
}

### List clients
GET http://localhost:3000/api/clients

### Get a client by id
GET http://localhost:3000/api/clients/1
# Authorization: 

### Update client (name) a client
PUT http://localhost:3000/api/clients/1
Content-Type: application/json
# Authorization: 

{
    "clientName": "Derrick Banners"
}

### Delete a client by id
DELETE  http://localhost:3000/api/clients/1
# Authorization: 


## Delegates CRUD
